theme: jekyll-theme-midnight
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - lesson1.md
  - lesson2.md

title: Easy websites with GitHub Pages and Markdown
description: Jay Brodeur | DASH Workshop | 13-February, 2020
